"""Modification of Example 8 which shows how to use an ORCA QC/MM potential."""

import os, os.path

from Definitions       import dataPathM
from pBabel            import ImportSystem
from pCore             import logFile      , \
                              Selection
from pMolecule.MMModel import MMModelOPLS
from pMolecule.NBModel import NBModelORCA
from pMolecule.QCModel import QCModelORCA

# . The ORCA QC Model is QCModelORCA. Its constructor takes both positional and keyword arguments.
#
#   The positional arguments are all strings and are keywords that are passed directly to the ORCA
#   program (without inspection). By convention, although not by necessity, the first positional
#   argument is of the form "method:basis" where method is the QC approximation and basis is the
#   name of the basis set. Valid ORCA combinations are "HF:6-31G", "MP2:6-311++G**" and "DFTEnergy+".
#   The latter is an ORCA keyword that specifies a particular combination of DFT functional and basis
#   set.
#
#   The following keyword arguments are permitted:
#
#   command        - this gives the command to run ORCA. Its default is "orca" and need not normally be changed.
#   deleteJobFiles - indicates whether ORCA-produced files are to be deleted when the energy model object ceases to exist.
#                    The default is to delete all files.
#   job            - this is name given to the intermediate job files that ORCA produces. The default value is "job". This
#                    argument will need to be employed if two pDynamo ORCA jobs are running simultaneously within the same
#                    scratch directory. Different jobs MUST be given different names.
#   scratch        - this is the name of the directory where intermediate files generated by ORCA are placed. It defaults to
#                    the value specified by the environment variable PDYNAMO3_SCRATCH.
#
# . To run in parallel add an extra positional argument "PALn" to the constructor. n is an integer between 2 and
#   8 that gives the number of processors on which to run. E.g. for two processors, use:
#
#   QCModelORCA ( "HF:6-31G*", "EXTREMESCF", "PAL2", "SCFCONV10" )
#
# . The ORCA NB Model is NBModelORCA. This NB model MUST be used for QC/MM calculations with ORCA. Its constructor
#   takes no (interesting) arguments.
#
# . Note on scratch names:
#
#   It has been noticed that ORCA itself can give an error when the name of the scratch directory is too long.
#   This occurs in the "%pcname" line of the ORCA input file. To cure this use a shorter name - either by resetting
#   the environment variable PDYNAMO3_SCRATCH or by explicitly passing a name to the model with the "scratch" option.
#

# . Header.
logFile.Header ( )

# . Define the MM, NB and QC models.
mmModel = MMModelOPLS.WithParameterSet ( "bookSmallExamples" )
nbModel = NBModelORCA.WithDefaults ( )
qcModel = QCModelORCA.WithOptions ( keywords = [ "B3LYP", "6-31G*", "EXTREMESCF", "SCFCONV10" ] )

# . Define the molecule.
molecule = ImportSystem ( os.path.join ( dataPathM, "mol", "waterDimer_cs.mol" ) )

# . Define the selection for the first molecule.
firstWater = Selection.FromIterable ( [ 0, 1, 2 ] )

# . Define the energy model.
molecule.DefineMMModel ( mmModel )
molecule.DefineQCModel ( qcModel, qcSelection = firstWater )
molecule.DefineNBModel ( nbModel )
molecule.Summary ( )

# . Calculate an energy.
molecule.Energy ( doGradients = True )

# . Footer.
logFile.Footer ( )
